/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  

  const { nodes, materials } = useSpline('https://prod.spline.design/035lYSYC8fMJcEX1/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#rgb(5 8 22 / var(--tw-bg-opacity))']} />
      <group {...props} dispose={null}>
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={materials['Text Material']}
          castShadow
          receiveShadow
          position={[720.57, 1556.96, 240.77]}
          rotation={[-0.37, -0.71, -0.73]}
          scale={1}
        />
        <mesh
          name="Shape 4"
          geometry={nodes['Shape 4'].geometry}
          material={materials['Shape 4 Material']}
          position={[640.53, 583.26, 740.53]}
          rotation={[-0.86, -0.77, -0.72]}
          scale={[1, 1, 1.44]}
        />
        <mesh
          name="Shape 3"
          geometry={nodes['Shape 3'].geometry}
          material={materials['Shape 3 Material']}
          position={[627.47, 509.72, 683.94]}
          rotation={[-2.2, -1.09, -2.46]}
          scale={[1, 1, 1.11]}
        />
        <mesh
          name="Shape 2"
          geometry={nodes['Shape 2'].geometry}
          material={materials['Shape 2 Material']}
          position={[675.04, 554.44, 788.47]}
          rotation={[-0.12, -1.17, -0.63]}
          scale={[1, 1, 1.11]}
        />
        <mesh
          name="Shape"
          geometry={nodes.Shape.geometry}
          material={materials['Shape Material']}
          position={[579.22, 646.91, 602.78]}
          rotation={[-0.01, -1.05, -0.35]}
          scale={1}
        />
        <group name="Brainstorming Wall" position={[854.4, 913.14, -516.86]} rotation={[0, -1.53, 0]} scale={1}>
          <group name="papers" position={[0, 103.39, 10.23]} scale={2.02}>
            <mesh
              name="Cube 11"
              geometry={nodes['Cube 11'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[43.84, 2.21, -0.62]}
              scale={[0.42, 0.42, 0.01]}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.green_v2}
              castShadow
              receiveShadow
              position={[-0.82, 9.12, -0.62]}
              scale={[0.42, 0.42, 0.01]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes['Cube 3'].geometry}
              material={materials.white_broken}
              castShadow
              receiveShadow
              position={[26.25, 16.55, -0.62]}
              rotation={[0, 0, -0.12]}
              scale={[1.36, 0.93, 0.03]}
            />
            <mesh
              name="Cube 2"
              geometry={nodes['Cube 2'].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[36.23, 20.5, 0.31]}
              rotation={[0, 0, 0]}
              scale={[0.29, 0.29, 0.01]}
            />
            <mesh
              name="Cube 9"
              geometry={nodes['Cube 9'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-61.53, -27.11, -0.62]}
              rotation={[0, 0, 0.21]}
              scale={[0.87, 0.65, 0.01]}
            />
            <mesh
              name="Cube 8"
              geometry={nodes['Cube 8'].geometry}
              material={materials.blue}
              castShadow
              receiveShadow
              position={[57.66, -25.99, -0.62]}
              rotation={[0, 0, 0.01]}
              scale={[0.87, 0.65, 0.01]}
            />
            <mesh
              name="Cube 10"
              geometry={nodes['Cube 10'].geometry}
              material={materials.green_v2}
              castShadow
              receiveShadow
              position={[59.5, 27.89, -0.62]}
              rotation={[0, 0, 0.02]}
              scale={[0.42, 0.49, 0.01]}
            />
            <mesh
              name="Cube 7"
              geometry={nodes['Cube 7'].geometry}
              material={materials.red_V1}
              castShadow
              receiveShadow
              position={[8.45, -16.39, -0.62]}
              rotation={[0, 0, 0.01]}
              scale={[0.42, 0.49, 0.01]}
            />
            <mesh
              name="Cube 5"
              geometry={nodes['Cube 5'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[-29.07, -7.56, -0.62]}
              rotation={[0, 0, -0.23]}
              scale={[0.42, 0.16, 0.01]}
            />
            <mesh
              name="Cube 6"
              geometry={nodes['Cube 6'].geometry}
              material={materials.darkblue}
              castShadow
              receiveShadow
              position={[-41, 20.33, -0.62]}
              rotation={[0, 0, 0.08]}
              scale={[0.42, 0.72, 0.01]}
            />
            <mesh
              name="Cube 4"
              geometry={nodes['Cube 4'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[-38.27, -12.55, -0.62]}
              rotation={[0, 0, 0.08]}
              scale={[0.42, 0.16, 0.01]}
            />
            <mesh
              name="Cube 21"
              geometry={nodes['Cube 21'].geometry}
              material={materials.brown_v1}
              castShadow
              receiveShadow
              position={[0, 0, 4.14]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[0.88, 0.88, 0.02]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[0, 0, -0.05]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={[0.88, 0.88, 0.02]}
            />
          </group>
          <group name="threads" position={[-32.59, 120.47, 13.74]} scale={2.02}>
            <mesh
              name="Cube 13"
              geometry={nodes['Cube 13'].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[-4.72, 12.34, 0.13]}
              rotation={[-0.03, 0.1, -1.93]}
              scale={[0.05, 4.37, 0.15]}
            />
            <mesh
              name="Cube 12"
              geometry={nodes['Cube 12'].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[1.44, -5.41, 0]}
              rotation={[-0.03, 0.1, -0.94]}
              scale={[0.05, 4.37, 0.15]}
            />
            <mesh
              name="Cube 111"
              geometry={nodes['Cube 111'].geometry}
              material={materials.red}
              castShadow
              receiveShadow
              position={[20.27, -7.79, -1.74]}
              rotation={[-0.03, 0.1, 0.35]}
              scale={[0.05, 3.29, 0.15]}
            />
          </group>
          <group name="pines" position={[-3.54, 116.34, 8.85]} scale={2.02}>
            <mesh
              name="Sphere 3"
              geometry={nodes['Sphere 3'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[59.16, -24.97, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 2"
              geometry={nodes['Sphere 2'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[61.32, 26.47, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 9"
              geometry={nodes['Sphere 9'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[-61.32, -26.47, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 8"
              geometry={nodes['Sphere 8'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[-26.86, -12.93, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 7"
              geometry={nodes['Sphere 7'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[-36.5, -17.64, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 6"
              geometry={nodes['Sphere 6'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[-40.15, 22, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 5"
              geometry={nodes['Sphere 5'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[1.25, 6.56, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere 4"
              geometry={nodes['Sphere 4'].geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[10.31, -18.29, 0]}
              scale={0.88}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials.brown_v2}
              castShadow
              receiveShadow
              position={[29.6, 20.3, 0]}
              scale={0.88}
            />
          </group>
        </group>
        <group name="Clock" position={[819.08, 538.35, -73.37]} rotation={[0, -1.47, 0]} scale={[0.31, 0.23, 0.31]}>
          <mesh
            name="numbers"
            geometry={nodes.numbers.geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[2.62, 70.73, 96.03]}
            scale={[5.01, 5.77, 5.01]}
          />
          <mesh
            name="button"
            geometry={nodes.button.geometry}
            material={materials.orange}
            castShadow
            receiveShadow
            position={[15.52, 108.21, 83.66]}
          />
          <group name="panels" position={[-0.7, 71.79, 95.02]} scale={1.68}>
            <mesh
              name="Rectangle 4"
              geometry={nodes['Rectangle 4'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[66.69, -18.02, 0]}
            />
            <mesh
              name="Rectangle 3"
              geometry={nodes['Rectangle 3'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[-22.17, -18.02, 0]}
            />
            <mesh
              name="Rectangle 41"
              geometry={nodes['Rectangle 41'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[22.17, -18.02, 0]}
            />
            <mesh
              name="Rectangle 2"
              geometry={nodes['Rectangle 2'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[-66.69, -18.02, 0]}
            />
            <mesh
              name="Rectangle 42"
              geometry={nodes['Rectangle 42'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[66.69, 18.02, 0]}
            />
            <mesh
              name="Rectangle 31"
              geometry={nodes['Rectangle 31'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[-22.17, 18.02, 0]}
            />
            <mesh
              name="Rectangle 43"
              geometry={nodes['Rectangle 43'].geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[22.17, 18.02, 0]}
            />
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials.black}
              castShadow
              receiveShadow
              position={[-66.69, 18.02, 0]}
            />
          </group>
          <mesh
            name="box"
            geometry={nodes.box.geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[-0.7, 72.66, -61.29]}
            scale={1.68}
          />
        </group>
        <group name="lavalamp" position={[838.9, 1335.14, -606.55]} rotation={[0, 0, 0]} scale={[1.17, 0.87, 0.91]}>
          <mesh
            name="lava"
            geometry={nodes.lava.geometry}
            material={materials.grey}
            castShadow
            receiveShadow
            position={[-0.77, 158.12, 0.85]}
          />
          <group name="glass" position={[0, 160.4, 0.85]} scale={0.57}>
            <mesh
              name="Cylinder 3"
              geometry={nodes['Cylinder 3'].geometry}
              material={materials.glass}
              castShadow
              receiveShadow
              position={[0, -82.44, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.78, 0.65, 0.78]}
            />
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials.glass}
              castShadow
              receiveShadow
              position={[0, 33.11, 0]}
              scale={[0.78, 1.83, 0.78]}
            />
          </group>
          <group name="base" position={[0, 59.51, 0.85]} scale={0.57}>
            <mesh
              name="Cylinder 2"
              geometry={nodes['Cylinder 2'].geometry}
              material={materials.grey}
              castShadow
              receiveShadow
              position={[0, 66.06, 0]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.65, 0.54, 0.65]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.grey}
              castShadow
              receiveShadow
              position={[0, -38.32, 0]}
              scale={[0.65, 1.52, 0.65]}
            />
          </group>
          <mesh
            name="toppiece"
            geometry={nodes.toppiece.geometry}
            material={materials.grey}
            castShadow
            receiveShadow
            position={[0, 248.34, 0.85]}
            scale={[0.27, 0.63, 0.27]}
          />
        </group>
        <group name="Bin Room" position={[533.12, 122.88, 206.75]} scale={[2.25, 2.53, 2.49]}>
          <mesh
            name="Pyramid"
            geometry={nodes.Pyramid.geometry}
            material={materials['yellow-light']}
            castShadow
            receiveShadow
            position={[2.21, 54.52, -7.09]}
            rotation={[0, -1.13, 2.09]}
            scale={0.39}
          />
          <mesh
            name="Pentagon"
            geometry={nodes.Pentagon.geometry}
            material={materials['blue-ish']}
            castShadow
            receiveShadow
            position={[-1.26, 68.73, 8.17]}
            rotation={[-1.35, 0.26, -Math.PI / 2]}
            scale={0.39}
          />
          <mesh
            name="Cube 22"
            geometry={nodes['Cube 22'].geometry}
            material={materials.blue}
            castShadow
            receiveShadow
            position={[0, 33.17, 6.68]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.39}
          />
        </group>
        <group
          name="shelf_double"
          position={[833.43, 1217.45, -327.02]}
          rotation={[Math.PI, -1.56, Math.PI]}
          scale={[1.49, 1.68, 1.49]}
        >
          <mesh
            name="Rectangle 21"
            geometry={nodes['Rectangle 21'].geometry}
            material={materials.light_brown}
            castShadow
            receiveShadow
            position={[-103.23, 64.85, -1]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Rectangle1"
            geometry={nodes.Rectangle1.geometry}
            material={materials.light_brown}
            castShadow
            receiveShadow
            position={[0.5, 0.24, -1]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group name="Plant" position={[823.19, 1226.93, -128.68]} rotation={[0, -0.01, 0]} scale={1}>
          <mesh
            name="ground"
            geometry={nodes.ground.geometry}
            material={materials.brown_v2}
            castShadow
            receiveShadow
            position={[3.36, 43.23, 7.46]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1.35}
          />
          <group name="leafplant" position={[0, 99.56, -12.62]} scale={1.79}>
            <mesh
              name="Cube 61"
              geometry={nodes['Cube 61'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[15.14, -7.28, -5.08]}
              rotation={[-0.48, -0.54, -0.3]}
              scale={[1.08, 0.98, 0.21]}
            />
            <mesh
              name="Cube 81"
              geometry={nodes['Cube 81'].geometry}
              material={materials.green}
              castShadow
              receiveShadow
              position={[-12.72, -10.41, 3.45]}
              rotation={[-2.28, 0.96, 2.38]}
              scale={[1.09, 0.95, 0.21]}
            />
            <mesh
              name="Cube 71"
              geometry={nodes['Cube 71'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[-4.75, -3.01, 1.3]}
              rotation={[-0.33, 0.56, 0.25]}
              scale={[1.09, 0.97, 0.21]}
            />
            <mesh
              name="Cube 51"
              geometry={nodes['Cube 51'].geometry}
              material={materials.green}
              castShadow
              receiveShadow
              position={[4.55, 1.36, -3.32]}
              rotation={[-0.29, 0, -0.04]}
              scale={[1.08, 0.97, 0.21]}
            />
            <mesh
              name="Cube 41"
              geometry={nodes['Cube 41'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[1, -3.45, 13.55]}
              rotation={[-2.9, -0.07, -3.11]}
              scale={[1.08, 0.97, 0.21]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[18.97, -7.16, 12.41]}
              rotation={[-2.56, -0.68, -2.65]}
              scale={[0.76, 0.76, 0.15]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes['Cube 23'].geometry}
              material={materials.green_v1}
              castShadow
              receiveShadow
              position={[21.73, 1.96, 0.79]}
              rotation={[-1.83, -1.32, -1.83]}
              scale={[0.76, 0.76, 0.15]}
            />
          </group>
          <group name="flowerpot" position={[3.6, 29.35, 0.09]} scale={1.79}>
            <mesh
              name="Cube 91"
              geometry={nodes['Cube 91'].geometry}
              material={materials.white_broken}
              castShadow
              receiveShadow
              position={[0, 3.32, 0]}
              scale={0.44}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials.brown_v1}
              castShadow
              receiveShadow
              position={[0, 3.32, 0]}
              scale={0.44}
            />
          </group>
        </group>
        <group
          name="object_office_bigmug"
          position={[574.69, 539.93, 141.33]}
          rotation={[Math.PI, -1.13, Math.PI]}
          scale={1}
        >
          <mesh
            name="liquid"
            geometry={nodes.liquid.geometry}
            material={materials.brown_v2}
            castShadow
            receiveShadow
            position={[-5.14, 47.8, 0.21]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.54}
          />
          <group name="bodymug" position={[4.92, 28.29, -0.6]} scale={1.53}>
            <mesh
              name="Torus"
              geometry={nodes.Torus.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[9.94, 0.86, 0.09]}
              scale={[0.71, 0.71, 1.38]}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-6.87, 0, 0]}
              scale={[0.49, 0.59, 0.49]}
            />
          </group>
        </group>
        <mesh
          name="Rectangle2"
          geometry={nodes.Rectangle2.geometry}
          material={materials['Rectangle2 Material']}
          castShadow
          receiveShadow
          position={[1.41, 111.76, 14.2]}
          rotation={[-Math.PI / 2, 0, -3.14]}
        />
        <group
          name="officechair"
          position={[167.52, 452.98, -406.87]}
          rotation={[0, 0.94, 0]}
          scale={[1.39, 1.3, 1.44]}
        >
          <mesh
            name="seat"
            geometry={nodes.seat.geometry}
            material={nodes.seat.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="cover under seat"
            geometry={nodes['cover under seat'].geometry}
            material={nodes['cover under seat'].material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="back"
            geometry={nodes.back.geometry}
            material={nodes.back.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="back top"
            geometry={nodes['back top'].geometry}
            material={nodes['back top'].material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <group name="armrest left" position={[115.92, -15.79, -4.24]} scale={0.08}>
            <mesh
              name="armrest_cilinder_side_L"
              geometry={nodes.armrest_cilinder_side_L.geometry}
              material={nodes.armrest_cilinder_side_L.material}
              castShadow
              receiveShadow
              position={[-1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_L"
              geometry={nodes.armrest_L.geometry}
              material={nodes.armrest_L.material}
              castShadow
              receiveShadow
              position={[-1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_L"
              geometry={nodes.armrest_Cylinder_L.geometry}
              material={nodes.armrest_Cylinder_L.material}
              castShadow
              receiveShadow
              position={[-1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_cover_up_L"
              geometry={nodes.armrest_Cylinder_cover_up_L.geometry}
              material={nodes.armrest_Cylinder_cover_up_L.material}
              castShadow
              receiveShadow
              position={[-1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_cover_down_L"
              geometry={nodes.armrest_Cylinder_cover_down_L.geometry}
              material={nodes.armrest_Cylinder_cover_down_L.material}
              castShadow
              receiveShadow
              position={[-1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
          </group>
          <group name="armrest right" position={[-120.04, -15.79, -4.24]} scale={0.08}>
            <mesh
              name="armrest_cilinder_side_R"
              geometry={nodes.armrest_cilinder_side_R.geometry}
              material={nodes.armrest_cilinder_side_R.material}
              castShadow
              receiveShadow
              position={[1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_R"
              geometry={nodes.armrest_R.geometry}
              material={nodes.armrest_R.material}
              castShadow
              receiveShadow
              position={[1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_R"
              geometry={nodes.armrest_Cylinder_R.geometry}
              material={nodes.armrest_Cylinder_R.material}
              castShadow
              receiveShadow
              position={[1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_cover_up_R"
              geometry={nodes.armrest_Cylinder_cover_up_R.geometry}
              material={nodes.armrest_Cylinder_cover_up_R.material}
              castShadow
              receiveShadow
              position={[1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
            <mesh
              name="armrest_Cylinder_cover_down_R"
              geometry={nodes.armrest_Cylinder_cover_down_R.geometry}
              material={nodes.armrest_Cylinder_cover_down_R.material}
              castShadow
              receiveShadow
              position={[1447.01, -2096.91, -379.44]}
              scale={63.64}
            />
          </group>
          <mesh
            name="Cylinder_in"
            geometry={nodes.Cylinder_in.geometry}
            material={nodes.Cylinder_in.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="Cylinder_out"
            geometry={nodes.Cylinder_out.geometry}
            material={nodes.Cylinder_out.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="Cylinder_cover"
            geometry={nodes.Cylinder_cover.geometry}
            material={nodes.Cylinder_cover.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="sphere"
            geometry={nodes.sphere.geometry}
            material={nodes.sphere.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <mesh
            name="Cylinder_down"
            geometry={nodes.Cylinder_down.geometry}
            material={nodes.Cylinder_down.material}
            castShadow
            receiveShadow
            position={[-2.06, -186.76, -35.17]}
            scale={5.19}
          />
          <group name="chair legs" position={[0, -232.94, 0]} scale={0.08}>
            <mesh
              name="chair_leg"
              geometry={nodes.chair_leg.geometry}
              material={nodes.chair_leg.material}
              castShadow
              receiveShadow
              position={[-25.29, 566.41, -431.4]}
              scale={63.64}
            />
            <mesh
              name="chair_leg1"
              geometry={nodes.chair_leg1.geometry}
              material={nodes.chair_leg1.material}
              castShadow
              receiveShadow
              position={[-25.29, 566.41, -431.4]}
              scale={63.64}
            />
            <mesh
              name="chair_leg2"
              geometry={nodes.chair_leg2.geometry}
              material={nodes.chair_leg2.material}
              castShadow
              receiveShadow
              position={[-25.29, 566.41, -431.4]}
              scale={63.64}
            />
            <mesh
              name="chair_leg3"
              geometry={nodes.chair_leg3.geometry}
              material={nodes.chair_leg3.material}
              castShadow
              receiveShadow
              position={[-25.29, 566.41, -431.4]}
              scale={63.64}
            />
            <mesh
              name="chair_leg4"
              geometry={nodes.chair_leg4.geometry}
              material={nodes.chair_leg4.material}
              castShadow
              receiveShadow
              position={[-25.29, 566.41, -431.4]}
              scale={63.64}
            />
            <group name="wheels" position={[0, -115.38, 0]}>
              <mesh
                name="wheel"
                geometry={nodes.wheel.geometry}
                material={nodes.wheel.material}
                castShadow
                receiveShadow
                position={[-25.29, 681.79, -431.4]}
                scale={63.64}
              />
              <mesh
                name="wheel1"
                geometry={nodes.wheel1.geometry}
                material={nodes.wheel1.material}
                castShadow
                receiveShadow
                position={[-25.29, 681.79, -431.4]}
                scale={63.64}
              />
              <mesh
                name="wheel2"
                geometry={nodes.wheel2.geometry}
                material={nodes.wheel2.material}
                castShadow
                receiveShadow
                position={[-25.29, 681.79, -431.4]}
                scale={63.64}
              />
              <mesh
                name="wheel3"
                geometry={nodes.wheel3.geometry}
                material={nodes.wheel3.material}
                castShadow
                receiveShadow
                position={[-25.29, 681.79, -431.4]}
                scale={63.64}
              />
              <mesh
                name="wheel4"
                geometry={nodes.wheel4.geometry}
                material={nodes.wheel4.material}
                castShadow
                receiveShadow
                position={[-25.29, 681.79, -431.4]}
                scale={63.64}
              />
            </group>
          </group>
          <group name="lever" position={[-53.16, -109.28, -22.02]} scale={0.08}>
            <mesh
              name="lever1"
              geometry={nodes.lever1.geometry}
              material={nodes.lever1.material}
              castShadow
              receiveShadow
              position={[626.68, -950.2, -161.36]}
              scale={63.64}
            />
            <mesh
              name="lever_top"
              geometry={nodes.lever_top.geometry}
              material={nodes.lever_top.material}
              castShadow
              receiveShadow
              position={[626.68, -950.2, -161.36]}
              scale={63.64}
            />
          </group>
        </group>
        <group
          name="object_office_tv 2"
          position={[908.24, 652.77, 325.78]}
          rotation={[2.97, -1.52, 2.97]}
          scale={[2.16, 2.05, 2.78]}
        >
          <group name="screws" position={[-2.66, 39.16, -34.59]}>
            <mesh
              name="Sphere 31"
              geometry={nodes['Sphere 31'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-18.42, -16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere 21"
              geometry={nodes['Sphere 21'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-18.42, 16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere 32"
              geometry={nodes['Sphere 32'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[18.42, -16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere1"
              geometry={nodes.Sphere1.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[18.42, 16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
          </group>
          <group name="arm" position={[-2.53, 38.77, 0]}>
            <mesh
              name="Cube 32"
              geometry={nodes['Cube 32'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 12.48, 29.34]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={0.18}
            />
            <mesh
              name="Cube 62"
              geometry={nodes['Cube 62'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 12.48, 30.98]}
              rotation={[0, 0, 0]}
              scale={[0.94, 0.94, 0.02]}
            />
            <mesh
              name="Cube 52"
              geometry={nodes['Cube 52'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, -7.19, -9.61]}
              rotation={[-1.23, 0, Math.PI]}
              scale={[0.11, 0.66, 0.1]}
            />
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, -1.19, 23.33]}
              rotation={[-2.53, 0, -Math.PI]}
              scale={[0.11, 0.66, 0.1]}
            />
            <mesh
              name="Cube 72"
              geometry={nodes['Cube 72'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 0, -35.24]}
              rotation={[0, 0, 0]}
              scale={[0.79, 0.79, 0.02]}
            />
          </group>
          <mesh
            name="screen"
            geometry={nodes.screen.geometry}
            material={materials['screen Material']}
            castShadow
            receiveShadow
            position={[0, 56.16, 35.78]}
            rotation={[0, 0, 0]}
            scale={[0.56, 0.52, 0]}
          />
          <group
            name="Screen code"
            position={[-0.15, 56.32, 37.27]}
            rotation={[Math.PI, -1.57, Math.PI]}
            scale={[1.49, 4, 4.86]}
          >
            <group name="Group" position={[0.14, 0.12, 1.58]} rotation={[0, 0.03, 0]}>
              <mesh
                name="Rectangle 22"
                geometry={nodes['Rectangle 22'].geometry}
                material={materials['Rectangle 22 Material']}
                castShadow
                receiveShadow
                position={[-2.52, 1.62, 7.5]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 23"
                geometry={nodes['Rectangle 23'].geometry}
                material={materials['Rectangle 23 Material']}
                castShadow
                receiveShadow
                position={[-2.92, -5.19, 2.22]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 24"
                geometry={nodes['Rectangle 24'].geometry}
                material={materials.blue}
                castShadow
                receiveShadow
                position={[-1, -7.63, 9.81]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 25"
                geometry={nodes['Rectangle 25'].geometry}
                material={materials['Rectangle 25 Material']}
                castShadow
                receiveShadow
                position={[0.33, 5.19, 9.73]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 26"
                geometry={nodes['Rectangle 26'].geometry}
                material={materials.blue}
                castShadow
                receiveShadow
                position={[-0.16, 7.49, -0.02]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 27"
                geometry={nodes['Rectangle 27'].geometry}
                material={materials['Rectangle 27 Material']}
                castShadow
                receiveShadow
                position={[-2.02, -0.58, 8.5]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
            </group>
            <mesh
              name="Sphere2"
              geometry={nodes.Sphere2.geometry}
              material={materials['Mat 7']}
              castShadow
              receiveShadow
              position={[0.12, 11.86, 14.24]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Sphere3"
              geometry={nodes.Sphere3.geometry}
              material={materials['Mat 6']}
              castShadow
              receiveShadow
              position={[0.12, 11.88, 15.9]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Sphere4"
              geometry={nodes.Sphere4.geometry}
              material={materials['Mat 5']}
              castShadow
              receiveShadow
              position={[0.11, 11.9, 17.6]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Rectangle 28"
              geometry={nodes['Rectangle 28'].geometry}
              material={materials['Rectangle 28 Material']}
              castShadow
              receiveShadow
              position={[-3.55, 0, -0.05]}
              rotation={[0.1, 1.56, -0.11]}
              scale={[0.44, 0.52, 0.44]}
            />
          </group>
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[0, 56.16, 33.92]}
            rotation={[0, -0.01, 0]}
            scale={[0.57, 0.53, 0.01]}
          />
        </group>
        <group
          name="object_office_tv"
          position={[886.04, 661.69, -155.68]}
          rotation={[0.08, -1.46, 0.08]}
          scale={[2.16, 2.05, 2.78]}
        >
          <group name="screws1" position={[-2.66, 39.16, -34.59]}>
            <mesh
              name="Sphere 33"
              geometry={nodes['Sphere 33'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-18.42, -16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere 22"
              geometry={nodes['Sphere 22'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-18.42, 16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere 34"
              geometry={nodes['Sphere 34'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[18.42, -16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
            <mesh
              name="Sphere5"
              geometry={nodes.Sphere5.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[18.42, 16.8, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.09, 0.09, 0.03]}
            />
          </group>
          <group name="arm1" position={[-2.53, 38.77, 0]}>
            <mesh
              name="Cube 33"
              geometry={nodes['Cube 33'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 12.48, 29.34]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={0.18}
            />
            <mesh
              name="Cube 63"
              geometry={nodes['Cube 63'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 12.48, 30.98]}
              rotation={[0, 0, 0]}
              scale={[0.94, 0.94, 0.02]}
            />
            <mesh
              name="Cube 53"
              geometry={nodes['Cube 53'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, -7.19, -9.61]}
              rotation={[-1.23, 0, Math.PI]}
              scale={[0.11, 0.66, 0.1]}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, -1.19, 23.33]}
              rotation={[-2.53, 0, -Math.PI]}
              scale={[0.11, 0.66, 0.1]}
            />
            <mesh
              name="Cube 73"
              geometry={nodes['Cube 73'].geometry}
              material={materials.greydarker}
              castShadow
              receiveShadow
              position={[0, 0, -35.24]}
              rotation={[0, 0, 0]}
              scale={[0.79, 0.79, 0.02]}
            />
          </group>
          <mesh
            name="screen1"
            geometry={nodes.screen1.geometry}
            material={materials['screen1 Material']}
            castShadow
            receiveShadow
            position={[0, 56.16, 35.78]}
            rotation={[0, 0, 0]}
            scale={[0.56, 0.52, 0]}
          />
          <group
            name="Screen code1"
            position={[-0.15, 56.32, 37.27]}
            rotation={[Math.PI, -1.57, Math.PI]}
            scale={[1.49, 4, 4.86]}
          >
            <group name="Group1" position={[0.14, 0.12, 1.58]} rotation={[0, 0.03, 0]}>
              <mesh
                name="Rectangle 29"
                geometry={nodes['Rectangle 29'].geometry}
                material={materials['Rectangle 29 Material']}
                castShadow
                receiveShadow
                position={[-2.52, 1.62, 7.5]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 210"
                geometry={nodes['Rectangle 210'].geometry}
                material={materials['Rectangle 210 Material']}
                castShadow
                receiveShadow
                position={[-2.92, -5.19, 2.22]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 211"
                geometry={nodes['Rectangle 211'].geometry}
                material={materials.blue}
                castShadow
                receiveShadow
                position={[-1, -7.63, 9.81]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 212"
                geometry={nodes['Rectangle 212'].geometry}
                material={materials['Rectangle 212 Material']}
                castShadow
                receiveShadow
                position={[0.33, 5.19, 9.73]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 213"
                geometry={nodes['Rectangle 213'].geometry}
                material={materials.blue}
                castShadow
                receiveShadow
                position={[-0.16, 7.49, -0.02]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
              <mesh
                name="Rectangle 214"
                geometry={nodes['Rectangle 214'].geometry}
                material={materials['Rectangle 214 Material']}
                castShadow
                receiveShadow
                position={[-2.02, -0.58, 8.5]}
                rotation={[0.1, 1.56, -0.11]}
                scale={[0.44, 0.48, 0.44]}
              />
            </group>
            <mesh
              name="Sphere6"
              geometry={nodes.Sphere6.geometry}
              material={materials['Mat 7']}
              castShadow
              receiveShadow
              position={[0.12, 11.86, 14.24]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Sphere7"
              geometry={nodes.Sphere7.geometry}
              material={materials['Mat 6']}
              castShadow
              receiveShadow
              position={[0.12, 11.88, 15.9]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Sphere8"
              geometry={nodes.Sphere8.geometry}
              material={materials['Mat 5']}
              castShadow
              receiveShadow
              position={[0.11, 11.9, 17.6]}
              rotation={[0.51, 1.56, -0.52]}
              scale={[0.27, 0.35, 0.37]}
            />
            <mesh
              name="Rectangle 215"
              geometry={nodes['Rectangle 215'].geometry}
              material={materials['Rectangle 215 Material']}
              castShadow
              receiveShadow
              position={[-3.55, 0, -0.05]}
              rotation={[0.1, 1.56, -0.11]}
              scale={[0.44, 0.52, 0.44]}
            />
          </group>
          <mesh
            name="body1"
            geometry={nodes.body1.geometry}
            material={materials.black}
            castShadow
            receiveShadow
            position={[0, 56.16, 33.92]}
            rotation={[0, -0.01, 0]}
            scale={[0.57, 0.53, 0.01]}
          />
        </group>
        <group
          name="Mouse"
          position={[574.54, 542.29, -46.67]}
          rotation={[-Math.PI, -0.15, -Math.PI]}
          scale={[0.45, 0.41, 0.38]}
        >
          <mesh
            name="Cylinder2"
            geometry={nodes.Cylinder2.geometry}
            material={materials['Cylinder2 Material']}
            castShadow
            receiveShadow
            position={[-44.83, 32.43, 10.02]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1.24}
          />
          <mesh
            name="Cube3"
            geometry={nodes.Cube3.geometry}
            material={materials['Cube3 Material']}
            castShadow
            receiveShadow
            position={[8.55, 47.37, 11.73]}
            scale={1.24}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-3108.301}
          shadow-camera-right={3108.301}
          shadow-camera-top={3108.301}
          shadow-camera-bottom={-3108.301}
          position={[-1062.85, 660.74, -476.86]}
        />
        <mesh
          name="Walls 2"
          geometry={nodes['Walls 2'].geometry}
          material={materials['Walls 2 Material']}
          castShadow
          receiveShadow
          position={[41.17, 96.16, -77.55]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.7}
        />
        <group name="Objects" position={[52.27, 796.33, -18.87]}>
          <mesh
            name="Rectangle 5"
            geometry={nodes['Rectangle 5'].geometry}
            material={materials['Rectangle 5 Material']}
            castShadow
            receiveShadow
            position={[483.08, -257.76, -217.52]}
            rotation={[-1.57, -0.01, 3.07]}
            scale={0.84}
          />
          <group name="books-1" position={[458.02, -127.14, -738.43]} rotation={[Math.PI, 1.57, -Math.PI]}>
            <mesh
              name="book-1"
              geometry={nodes['book-1'].geometry}
              material={materials['book-1 Material']}
              castShadow
              receiveShadow
              position={[-42.13, -51.79, -35.07]}
              rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="book-2"
              geometry={nodes['book-2'].geometry}
              material={materials['book-2 Material']}
              castShadow
              receiveShadow
              position={[70.6, 0.51, 0]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="book-3"
              geometry={nodes['book-3'].geometry}
              material={materials['book-3 Material']}
              castShadow
              receiveShadow
              position={[45.7, -33.99, -18.42]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="book-4"
              geometry={nodes['book-4'].geometry}
              material={materials['book-4 Material']}
              castShadow
              receiveShadow
              position={[5.73, -27.49, -18.42]}
              rotation={[-Math.PI / 2, -1.48, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="books-2" position={[661.13, -240.59, 265.12]} rotation={[0, 0.36, 0]}>
            <mesh
              name="paper 2"
              geometry={nodes['paper 2'].geometry}
              material={materials['paper 2 Material']}
              castShadow
              receiveShadow
              position={[-21.38, -15.18, 12.29]}
              rotation={[-Math.PI / 2, 0, -1.31]}
              scale={1}
            />
            <mesh
              name="paper"
              geometry={nodes.paper.geometry}
              material={materials['paper Material']}
              castShadow
              receiveShadow
              position={[8.89, -14.38, 22.3]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
            <group
              name="book-5"
              position={[41.7, 0, -27.45]}
              rotation={[-0.01, -0.18, -1.57]}
              scale={[0.74, 1.35, 1.23]}
            >
              <mesh
                name="Rectangle3"
                geometry={nodes.Rectangle3.geometry}
                material={materials['Rectangle3 Material']}
                castShadow
                receiveShadow
                position={[-22.7, 32.77, 1.79]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                name="Cube 44"
                geometry={nodes['Cube 44'].geometry}
                material={materials['Cube 44 Material']}
                castShadow
                receiveShadow
                position={[-0.32, 0.86, 0.42]}
                rotation={[0, 0, 0]}
                scale={[0.99, 1.01, 1]}
              />
              <mesh
                name="Cube 45"
                geometry={nodes['Cube 45'].geometry}
                material={materials['Cube 45 Material']}
                castShadow
                receiveShadow
                position={[-16.68, -0.27, 9.75]}
                rotation={[0, 0, 0]}
                scale={[0.99, 1.01, 1]}
              />
            </group>
          </group>
          <group name="computer" position={[645.56, -201.85, -542.63]} rotation={[0, -1.14, 0]}>
            <mesh
              name="Rectangle 216"
              geometry={nodes['Rectangle 216'].geometry}
              material={materials['Rectangle 216 Material']}
              castShadow
              receiveShadow
              position={[261.32, -51.95, 257.18]}
              rotation={[1.57, 0, -1.37]}
              scale={0.84}
            />
            <group name="Group2" position={[-1.33, 89.68, -11.15]} rotation={[0, 0.67, 0]} scale={1}>
              <group
                name="Screen code2"
                position={[41.86, 48.11, -51.84]}
                rotation={[3.13, -0.9, -2.97]}
                scale={[2.81, 6.1, 6.51]}
              >
                <group name="Group3" position={[0.14, 0.12, 1.58]} rotation={[0, 0.03, 0]}>
                  <mesh
                    name="Rectangle 217"
                    geometry={nodes['Rectangle 217'].geometry}
                    material={materials['Rectangle 217 Material']}
                    castShadow
                    receiveShadow
                    position={[-2.52, 1.62, 7.5]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                  <mesh
                    name="Rectangle 218"
                    geometry={nodes['Rectangle 218'].geometry}
                    material={materials['Rectangle 218 Material']}
                    castShadow
                    receiveShadow
                    position={[-2.92, -5.19, 2.22]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                  <mesh
                    name="Rectangle 219"
                    geometry={nodes['Rectangle 219'].geometry}
                    material={materials.blue}
                    castShadow
                    receiveShadow
                    position={[-1, -7.63, 9.81]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                  <mesh
                    name="Rectangle 220"
                    geometry={nodes['Rectangle 220'].geometry}
                    material={materials['Rectangle 220 Material']}
                    castShadow
                    receiveShadow
                    position={[0.33, 5.19, 9.73]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                  <mesh
                    name="Rectangle 221"
                    geometry={nodes['Rectangle 221'].geometry}
                    material={materials.blue}
                    castShadow
                    receiveShadow
                    position={[-0.16, 7.49, -0.02]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                  <mesh
                    name="Rectangle 222"
                    geometry={nodes['Rectangle 222'].geometry}
                    material={materials['Rectangle 222 Material']}
                    castShadow
                    receiveShadow
                    position={[-2.02, -0.58, 8.5]}
                    rotation={[0.1, 1.56, -0.11]}
                    scale={[0.44, 0.48, 0.44]}
                  />
                </group>
                <mesh
                  name="Sphere9"
                  geometry={nodes.Sphere9.geometry}
                  material={materials['Mat 7']}
                  castShadow
                  receiveShadow
                  position={[0.12, 11.86, 14.24]}
                  rotation={[0.51, 1.56, -0.52]}
                  scale={[0.27, 0.35, 0.37]}
                />
                <mesh
                  name="Sphere10"
                  geometry={nodes.Sphere10.geometry}
                  material={materials['Mat 6']}
                  castShadow
                  receiveShadow
                  position={[0.12, 11.88, 15.9]}
                  rotation={[0.51, 1.56, -0.52]}
                  scale={[0.27, 0.35, 0.37]}
                />
                <mesh
                  name="Sphere11"
                  geometry={nodes.Sphere11.geometry}
                  material={materials['Mat 5']}
                  castShadow
                  receiveShadow
                  position={[0.11, 11.9, 17.6]}
                  rotation={[0.51, 1.56, -0.52]}
                  scale={[0.27, 0.35, 0.37]}
                />
                <mesh
                  name="Rectangle 223"
                  geometry={nodes['Rectangle 223'].geometry}
                  material={materials['Rectangle 223 Material']}
                  castShadow
                  receiveShadow
                  position={[-3.55, 0, -0.05]}
                  rotation={[0.1, 1.56, -0.11]}
                  scale={[0.44, 0.52, 0.44]}
                />
              </group>
              <mesh
                name="Rectangle 6"
                geometry={nodes['Rectangle 6'].geometry}
                material={materials['Rectangle 6 Material']}
                castShadow
                receiveShadow
                position={[51.06, 42.6, -64.21]}
                rotation={[-0.22, -0.66, -1.71]}
                scale={0.84}
              />
              <mesh
                name="Rectangle 61"
                geometry={nodes['Rectangle 61'].geometry}
                material={materials['Rectangle 61 Material']}
                position={[46.82, 46.53, -58.45]}
                rotation={[-0.22, -0.66, -0.14]}
                scale={0.84}
              />
            </group>
            <mesh
              name="Cube 74"
              geometry={nodes['Cube 74'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-139.98, -2.99, -81.82]}
              rotation={[-Math.PI, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Rectangle4"
              geometry={nodes.Rectangle4.geometry}
              material={materials['Rectangle4 Material']}
              castShadow
              receiveShadow
              position={[-1.75, 22.8, -18.79]}
              rotation={[-1.13, 0, -Math.PI / 2]}
              scale={0.84}
            />
            <mesh
              name="Rectangle 44"
              geometry={nodes['Rectangle 44'].geometry}
              material={materials['Rectangle 44 Material']}
              castShadow
              receiveShadow
              position={[-1.75, 7.43, 4.01]}
              rotation={[-1.13, 0, -Math.PI / 2]}
              scale={0.84}
            />
            <mesh
              name="Cube 75"
              geometry={nodes['Cube 75'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-134.32, -2.99, -83.82]}
              rotation={[-Math.PI, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 64"
              geometry={nodes['Cube 64'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[139.49, -2.99, -83.54]}
              rotation={[-Math.PI, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 76"
              geometry={nodes['Cube 76'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-139.92, -46.3, -3.35]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 54"
              geometry={nodes['Cube 54'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[139.55, -46.3, -5.06]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 46"
              geometry={nodes['Cube 46'].geometry}
              material={materials['Cube 46 Material']}
              castShadow
              receiveShadow
              position={[0, 2.04, 0]}
              rotation={[-1.13, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="cd-4" position={[607.17, -347.28, 688.92]} rotation={[-Math.PI / 2, 0, 0]} scale={0.78}>
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[46.2, -124.61, 7.27]}
              rotation={[0, 0, -1.75]}
              scale={1.28}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-89.13, -155.17, 5.27]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={1.28}
            />
            <mesh
              name="Cylinder3"
              geometry={nodes.Cylinder3.geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[86.56, -127.47, 7.09]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={1.28}
            />
            <mesh
              name="Rectangle 224"
              geometry={nodes['Rectangle 224'].geometry}
              material={materials['Rectangle 224 Material']}
              castShadow
              receiveShadow
              position={[4.53, -22.14, -42.46]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1.28}
            />
            <mesh
              name="红色"
              geometry={nodes.红色.geometry}
              material={materials['red-cd']}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[-1.94, -1.51, 2.72]}
              scale={[0.72, 0.09, 0.72]}
            />
            <mesh
              name="Cylinder4"
              geometry={nodes.Cylinder4.geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[0.72, 0.09, 0.72]}
            />
          </group>
          <group name="cd-2" position={[637.14, -589.39, 708.33]}>
            <mesh
              name="Cube 34"
              geometry={nodes['Cube 34'].geometry}
              material={materials['blue-a-2']}
              castShadow
              receiveShadow
              position={[19.06, -84.98, 74.49]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Cube 24"
              geometry={nodes['Cube 24'].geometry}
              material={materials['blue-a-2']}
              castShadow
              receiveShadow
              position={[-1.65, -21.84, -37.69]}
              rotation={[-0.09, -Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials['Cube5 Material']}
              castShadow
              receiveShadow
              position={[-8.36, -3.84, -108.49]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <group name="Group 19" position={[6.89, 10.69, 22.42]}>
              <mesh
                name="Ellipse 2"
                geometry={nodes['Ellipse 2'].geometry}
                material={materials['Ellipse 2 Material']}
                castShadow
                receiveShadow
                position={[-3.29, 7.18, 12.66]}
                rotation={[-0.59, -0.18, -1.73]}
                scale={0.77}
              />
              <mesh
                name="Cube 25"
                geometry={nodes['Cube 25'].geometry}
                material={materials['Cube 25 Material']}
                castShadow
                receiveShadow
                position={[0, 0, 0]}
                rotation={[-0.59, -0.18, -0.16]}
                scale={0.77}
              />
            </group>
          </group>
          <group name="cd-3" position={[783.07, 439.55, -315.52]} scale={[0.38, 0.45, 0.38]}>
            <group name="Group 16" position={[-24.94, 0, 29.89]} rotation={[0.01, 0.26, 0.2]} scale={1}>
              <mesh
                name="Ellipse 3"
                geometry={nodes['Ellipse 3'].geometry}
                material={materials['main1-1']}
                castShadow
                receiveShadow
                position={[1.17, 7.28, 25.65]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Ellipse 21"
                geometry={nodes['Ellipse 21'].geometry}
                material={materials['main1-1']}
                castShadow
                receiveShadow
                position={[1.17, 7.28, -24.94]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Rectangle 32"
                geometry={nodes['Rectangle 32'].geometry}
                material={materials['main-3']}
                castShadow
                receiveShadow
                position={[1.51, 6.49, 0.49]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Rectangle 225"
                geometry={nodes['Rectangle 225'].geometry}
                material={materials['Rectangle 225 Material']}
                castShadow
                receiveShadow
                position={[10.61, 5.37, -0.01]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.94, 1, 1]}
              />
              <mesh
                name="Rectangle5"
                geometry={nodes.Rectangle5.geometry}
                material={materials['Rectangle5 Material']}
                castShadow
                receiveShadow
                position={[0, -5.23, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.94, 1, 1]}
              />
            </group>
            <group name="Group 13" position={[32.49, -9.1, -33.06]} rotation={[0, -0.17, 0]} scale={1}>
              <mesh
                name="Ellipse 31"
                geometry={nodes['Ellipse 31'].geometry}
                material={materials['main1-1']}
                castShadow
                receiveShadow
                position={[0.76, 7.99, 25.68]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Ellipse 22"
                geometry={nodes['Ellipse 22'].geometry}
                material={materials['main1-1']}
                castShadow
                receiveShadow
                position={[0.76, 7.99, -24.92]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Rectangle 33"
                geometry={nodes['Rectangle 33'].geometry}
                material={materials['main-3']}
                castShadow
                receiveShadow
                position={[1.23, 7.16, 0.5]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Rectangle 226"
                geometry={nodes['Rectangle 226'].geometry}
                material={materials.purple}
                castShadow
                receiveShadow
                position={[10.5, 5.78, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.94, 1, 1]}
              />
              <mesh
                name="Rectangle6"
                geometry={nodes.Rectangle6.geometry}
                material={materials['main-3']}
                castShadow
                receiveShadow
                position={[0, -5.23, 0]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.94, 1, 1]}
              />
            </group>
          </group>
          <group name="earphone" position={[448.96, -238.75, 375.22]} rotation={[-0.03, 0.15, -0.13]} scale={1}>
            <group name="Group 50" position={[-38.67, 10.21, 105.47]} rotation={[-0.08, 0.47, -1.6]} scale={0.84}>
              <mesh
                name="Rectangle 34"
                geometry={nodes['Rectangle 34'].geometry}
                material={materials['Rectangle 34 Material']}
                castShadow
                receiveShadow
                position={[-1.2, -0.12, 15.36]}
              />
              <mesh
                name="Rectangle 227"
                geometry={nodes['Rectangle 227'].geometry}
                material={materials['Rectangle 227 Material']}
                castShadow
                receiveShadow
                position={[-1.2, -0.12, 8.51]}
              />
              <mesh
                name="Cube6"
                geometry={nodes.Cube6.geometry}
                material={materials['Cube6 Material']}
                castShadow
                receiveShadow
                position={[0, 0, -7.36]}
              />
            </group>
            <group name="Group 51" position={[-111.24, 1.41, -9.91]} rotation={[3.07, -0.73, 1.6]} scale={0.84}>
              <mesh
                name="Rectangle 35"
                geometry={nodes['Rectangle 35'].geometry}
                material={materials['Rectangle 35 Material']}
                castShadow
                receiveShadow
                position={[-1.2, -0.12, 15.36]}
              />
              <mesh
                name="Rectangle 228"
                geometry={nodes['Rectangle 228'].geometry}
                material={materials['Rectangle 228 Material']}
                castShadow
                receiveShadow
                position={[-1.2, -0.12, 8.51]}
              />
              <mesh
                name="Cube7"
                geometry={nodes.Cube7.geometry}
                material={materials['Cube7 Material']}
                castShadow
                receiveShadow
                position={[0, 0, -7.36]}
              />
            </group>
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials['Cylinder 22 Material']}
              castShadow
              receiveShadow
              position={[-108.14, 0.25, -37.35]}
              rotation={[-1.66, 0.02, -0.76]}
              scale={1.2}
            />
            <mesh
              name="Cylinder5"
              geometry={nodes.Cylinder5.geometry}
              material={materials['Cylinder5 Material']}
              castShadow
              receiveShadow
              position={[-14.86, 11.43, 113.34]}
              rotation={[-1.66, 0.02, -1.19]}
              scale={1.2}
            />
            <mesh
              name="Torus1"
              geometry={nodes.Torus1.geometry}
              material={materials['Torus1 Material']}
              castShadow
              receiveShadow
              position={[-46.36, 3.62, 28.47]}
              rotation={[-1.66, 0.02, -2.59]}
              scale={[1.26, 1.2, 1.2]}
            />
          </group>
          <group name="table-2" position={[619.15, -528.41, 711.6]} scale={[1, 1, 0.93]}>
            <mesh
              name="Cube 101"
              geometry={nodes['Cube 101'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[153.32, -19.95, -182.84]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1.07, 1, 1]}
            />
            <mesh
              name="Cube 82"
              geometry={nodes['Cube 82'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[153.32, -19.95, 175.5]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1.07, 1, 1]}
            />
            <mesh
              name="Cube 102"
              geometry={nodes['Cube 102'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-152.28, -19.95, -182.84]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1.07, 1, 1]}
            />
            <mesh
              name="Cube 77"
              geometry={nodes['Cube 77'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-152.28, -19.95, 175.5]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[1.07, 1, 1]}
            />
            <mesh
              name="Cube 121"
              geometry={nodes['Cube 121'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[154.21, -149.51, 4.45]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.32, 1, 1]}
            />
            <mesh
              name="Cube 112"
              geometry={nodes['Cube 112'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[-151.03, -149.51, 4.45]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.32, 1, 1]}
            />
            <mesh
              name="Cube 103"
              geometry={nodes['Cube 103'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[3.75, -149.51, -182.84]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1, 1]}
            />
            <mesh
              name="Cube 92"
              geometry={nodes['Cube 92'].geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[3.75, -149.51, 175.56]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.25, 1, 1]}
            />
            <mesh
              name="Cube 55"
              geometry={nodes['Cube 55'].geometry}
              material={materials['bule-b-2']}
              castShadow
              receiveShadow
              position={[0, 131.01, -3.46]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="cd-5" position={[538.66, 123.91, -839.84]} scale={[0.72, 0.72, 0.33]}>
            <mesh
              name="红色1"
              geometry={nodes.红色1.geometry}
              material={materials.paper}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[1, 0.28, 1]}
            />
            <mesh
              name="Cylinder6"
              geometry={nodes.Cylinder6.geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[1, 0.28, 1]}
            />
          </group>
          <group name="cd-6" position={[538.66, 473.74, -839.84]} scale={[1, 1, 0.47]}>
            <mesh
              name="红色2"
              geometry={nodes.红色2.geometry}
              material={materials['red-cd']}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[1, 0.28, 1]}
            />
            <mesh
              name="Cylinder7"
              geometry={nodes.Cylinder7.geometry}
              material={materials['main-3']}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[1, 0.28, 1]}
            />
          </group>
          <group name="Guitar" position={[801.33, 280.93, 727.76]} rotation={[-2.14, -1.56, -2.15]} scale={1.09}>
            <mesh
              name="Ellipse 23"
              geometry={nodes['Ellipse 23'].geometry}
              material={materials['Ellipse 23 Material']}
              castShadow
              receiveShadow
              position={[-1.14, -159.01, 13.66]}
              rotation={[-0.01, 0, -0.01]}
              scale={0.92}
            />
            <mesh
              name="Shape 41"
              geometry={nodes['Shape 41'].geometry}
              material={materials['Shape 41 Material']}
              castShadow
              receiveShadow
              position={[-35, -254.35, 4.48]}
            />
            <mesh
              name="Shape 31"
              geometry={nodes['Shape 31'].geometry}
              material={materials['Shape 31 Material']}
              castShadow
              receiveShadow
              position={[-25.83, -106.07, 3.57]}
              rotation={[0, 0, 0]}
              scale={1}
            />
            <mesh
              name="Shape 21"
              geometry={nodes['Shape 21'].geometry}
              material={materials['Shape 21 Material']}
              castShadow
              receiveShadow
              position={[-82, -132.42, -38.9]}
            />
          </group>
          <group name="lamp" position={[-812.67, -107.53, -582.18]} rotation={[0, 1.22, 0]} scale={1.67}>
            <mesh
              name="Sphere 23"
              geometry={nodes['Sphere 23'].geometry}
              material={materials['Sphere 23 Material']}
              castShadow
              receiveShadow
              position={[-62.28, 256.7, 49.13]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 78"
              geometry={nodes['Cube 78'].geometry}
              material={materials['Cube 78 Material']}
              castShadow
              receiveShadow
              position={[-51.78, 282.28, 41.49]}
              rotation={[0, 0.7, Math.PI / 3]}
              scale={1}
            />
            <mesh
              name="Cube 65"
              geometry={nodes['Cube 65'].geometry}
              material={materials['Cube 65 Material']}
              castShadow
              receiveShadow
              position={[47.95, -248.79, -37.78]}
              rotation={[0, 0.7, 0]}
            />
            <mesh
              name="Cylinder 23"
              geometry={nodes['Cylinder 23'].geometry}
              material={materials['Cylinder 23 Material']}
              castShadow
              receiveShadow
              position={[49.13, -333.68, -36.39]}
              rotation={[0, 0.7, 0]}
            />
          </group>
          <group name="music-ui" position={[781.65, 315.38, 198.38]} scale={[1, 0.81, 1]}>
            <mesh
              name="Rectangle7"
              geometry={nodes.Rectangle7.geometry}
              material={materials['Rectangle7 Material']}
              castShadow
              receiveShadow
              position={[6.78, 0.85, -0.04]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[1, 1.23, 1]}
            />
            <mesh
              name="Rectangle 14"
              geometry={nodes['Rectangle 14'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, 153.06]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 13"
              geometry={nodes['Rectangle 13'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, 118.96]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 12"
              geometry={nodes['Rectangle 12'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, 85.38]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 11"
              geometry={nodes['Rectangle 11'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, 51.67]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 10"
              geometry={nodes['Rectangle 10'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, 17.57]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 9"
              geometry={nodes['Rectangle 9'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, -16.45]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 8"
              geometry={nodes['Rectangle 8'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, -49.15]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 7"
              geometry={nodes['Rectangle 7'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, -83.51]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 62"
              geometry={nodes['Rectangle 62'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, -117.15]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 51"
              geometry={nodes['Rectangle 51'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-0.18, -4.68, -151]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <group name="button-ui" position={[807.75, 471.21, 496.06]} scale={[1.42, 1.4, 1.42]}>
            <mesh
              name="Ellipse 32"
              geometry={nodes['Ellipse 32'].geometry}
              material={materials['ui-2']}
              castShadow
              receiveShadow
              position={[-6.99, 140.05, 1.44]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={0.59}
            />
            <mesh
              name="Rectangle 63"
              geometry={nodes['Rectangle 63'].geometry}
              material={materials['main1-1']}
              castShadow
              receiveShadow
              position={[-7.07, -31, 0]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              name="Rectangle 52"
              geometry={nodes['Rectangle 52'].geometry}
              material={materials['Rectangle 52 Material']}
              castShadow
              receiveShadow
              position={[9.48, -26, 0]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
          <group name="photo-2" position={[144.3, 304.54, -835.3]}>
            <mesh
              name="Rectangle 36"
              geometry={nodes['Rectangle 36'].geometry}
              material={materials['blue-a-2']}
              castShadow
              receiveShadow
              position={[0, 0, -11.73]}
              scale={0.89}
            />
            <mesh
              name="Rectangle8"
              geometry={nodes.Rectangle8.geometry}
              material={materials.paper}
              castShadow
              receiveShadow
              position={[1.43, 0, 10.85]}
              scale={0.89}
            />
          </group>
          <group name="window" position={[-410.64, 255.29, -836.04]}>
            <mesh
              name="Cube 47"
              geometry={nodes['Cube 47'].geometry}
              material={materials['Cube 47 Material']}
              castShadow
              receiveShadow
              position={[0.63, 0.94, -10.81]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 56"
              geometry={nodes['Cube 56'].geometry}
              material={materials['Cube 56 Material']}
              castShadow
              receiveShadow
              position={[1.69, 105.58, 0]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="窗户"
              geometry={nodes.窗户.geometry}
              material={materials['窗户 Material']}
              castShadow
              receiveShadow
              position={[0, -198.5, 9.16]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="窗户1"
              geometry={nodes.窗户1.geometry}
              material={materials['窗户1 Material']}
              castShadow
              receiveShadow
              position={[0, -198.5, -46.84]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="table" position={[566.56, -470.16, -221.28]} scale={0.7}>
            <mesh
              name="Cube 35"
              geometry={nodes['Cube 35'].geometry}
              material={materials['Cube 35 Material']}
              castShadow
              receiveShadow
              position={[231.35, -29.75, -676.32]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.42}
            />
            <mesh
              name="Cube 36"
              geometry={nodes['Cube 36'].geometry}
              material={materials['Cube 36 Material']}
              castShadow
              receiveShadow
              position={[-249.64, -29.75, -676.32]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.42}
            />
            <mesh
              name="Cube 26"
              geometry={nodes['Cube 26'].geometry}
              material={materials['Cube 26 Material']}
              castShadow
              receiveShadow
              position={[231.35, -29.75, 886.09]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.42}
            />
            <mesh
              name="Cube8"
              geometry={nodes.Cube8.geometry}
              material={materials['Cube8 Material']}
              castShadow
              receiveShadow
              position={[-249.64, -29.75, 886.09]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1.42}
            />
            <mesh
              name="Rectangle9"
              geometry={nodes.Rectangle9.geometry}
              material={materials['Rectangle9 Material']}
              castShadow
              receiveShadow
              position={[0, 230.16, 109]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="carpet " position={[-256.11, -681.27, 145.27]} scale={0.96}>
            <mesh
              name="Ellipse 33"
              geometry={nodes['Ellipse 33'].geometry}
              material={materials['Ellipse 33 Material']}
              castShadow
              receiveShadow
              position={[0, 10.56, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.09, 1.09, 1.66]}
            />
            <mesh
              name="Ellipse 24"
              geometry={nodes['Ellipse 24'].geometry}
              material={materials['Ellipse 24 Material']}
              castShadow
              receiveShadow
              position={[0, 7.39, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.09, 1.09, 1.66]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials['Ellipse Material']}
              castShadow
              receiveShadow
              position={[0, -7.39, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.09, 1.09, 1.66]}
            />
          </group>
        </group>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.44}
          far={100000}
          near={-100000}
          position={[-3223.11, 2977.24, 3587.79]}
          rotation={[-0.53, -0.67, -0.34]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.71} color="#eaeaea" />
      </group>
    </>
  )
}
